name: Go Tests

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      go-version:
        required: false
        type: string
        default: "1.23"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./... -v
